name: 'Automation of NU Health Management System'

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

jobs:
  ubuntu-test:
    env:
      SCHOOL_ID: ${{ secrets.SCHOOL_ID }}
      SCHOOL_PASSWD: ${{ secrets.SCHOOL_PASSWD }}
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: 'Set current datetime as env variable'
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y/%m/%d(%a) %H:%M:%S')" >> $GITHUB_ENV

      - uses: k5-mot/auto-hms-action@main
        if: ${{ env.SCHOOL_ID }} != null && ${{ env.SCHOOL_PASSWD }} != null
        with:
          SCHOOL_ID: ${{ env.SCHOOL_ID }}
          SCHOOL_PASSWD: ${{ env.SCHOOL_PASSWD }}

      - uses: sarisia/actions-status-discord@v1
        if: always() && ${{ env.DISCORD_WEBHOOK }} != null
        with:
          webhook: ${{ env.DISCORD_WEBHOOK }}
          title: ü¶æ `${{ github.actor }}` - ÂÅ•Â∫∑ÁÆ°ÁêÜ„Ç∑„Çπ„ÉÜ„É† Ëá™ÂãïÂÖ•ÂäõÂÆå‰∫Ü
          username: 'Auto-HMS'
          avatar_url: 'https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png'
          image: 'https://source.unsplash.com/4_jhDO54BYg/1080x520'
          nocontext: true
          noprefix: true
          description: |
            `${{ env.CURRENT_DATETIME }}` ([GitHub](https://github.com/k5-mot/auto-hms-action)) ([NU-HMS](https://hms.hc.nagasaki-u.ac.jp/))



# avatar_url: 'https://app.pixelencounter.com/api/basic/monsters/random/png?size=1000'
# image: 'https://lh3.googleusercontent.com/pw/AM-JKLWX45liujf0wXuzjCFc4SKoOiKqNsxID7ddKZFAsf-4-3qPFMsNj7sBYITyKqfm7ZzsB8jbPSOMb7J0cMGaVQ7p03TvxcfPgdOYPmSNx0t-RxZhJGiVMqMKHKWhH3U-Yy6piDsgZCFp4Z0OpJDkvC9e=w2048-h1361-no?authuser=0'
# image: 'https://pbs.twimg.com/profile_banners/1159383628951851008/1565318066/1080x360'

